name: Create macOS Build

on:
  push:
    branches:
      - "132-ci-build"
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-15-intel

    steps:
      - name: Install LLVM
        run: brew install llvm
  
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Configure Project
        run: cmake -B ${{github.workspace}}/build
      
      - name: Build Project
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Authenticating CLI...
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh auth login --with-token "${GITHUB_TOKEN}"

      - name: Creating Release...
        env:
        #  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TAG: ${{github.ref_name}}
        run: |
          gh release create "${TAG}" "${{github.workspace}}/build/brb" \
            --title "dummy release" \
            --notes-file "${{github.workspace}}/docs/Notes.md"

      #- name: Uploading Artefacts...
      #  env:
      #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #    TAG: ${{github.ref_name}}
      #  run: |
      #    gh release upload "${TAG}" \
      #      build/brb